version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: rentconnect-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentconnect
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .  # Должен быть `Dockerfile` внутри backend/
    container_name: rentconnect-backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rentconnect
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"


#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: rentconnect-pgadmin
#    depends_on:
#      - postgres
#    ports:
#      - "5050:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@rentconnect.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      - rentconnect-network

#networks:
#  rentconnect-network:
#    driver: bridge

volumes:
  postgres_data:
#  pgadmin_data:

