# Server Configuration
server:
  port: 8080

# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/rentconnect
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
          client:
            registration:
              google:
                client-id: YOUR_GOOGLE_CLIENT_ID
                client-secret: YOUR_GOOGLE_CLIENT_SECRET
                scope: email,profile
              github:
                client-id: YOUR_GITHUB_CLIENT_ID
                client-secret: YOUR_GITHUB_CLIENT_SECRET
                scope: user:email,read:user

# JWT Configuration
rentconnect:
  app:
    jwtSecret: "c2VjcmV0c3VwZXJzZWN1cmVrZXltdXN0YmU2NGVuY29kZWQ="
    jwtExpirationMs: 86400000
    frontendUrl: http://localhost:3000

# OAuth2 Configuration

# Frontend URL for OAuth2 redirect

# Logging Configuration
management:
  endpoints:
    web:
      exposure:
        include: mappings
logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html